package biotrack.service;

import biotrack.model.User;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

import javax.imageio.ImageIO;
import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;

/**
 * Compact, printable Emergency Health Card - wallet/ID-card sized (3.375in x
 * 2.125in, standard credit-card dimensions), separate from the full PDF
 * health report. Meant to be printed and carried, not read on screen.
 */
public class EmergencyCardGenerator {

    // Standard ID-card size in PDF points (72 pt/inch).
    private static final float CARD_WIDTH = 3.375f * 72;
    private static final float CARD_HEIGHT = 2.125f * 72;
    private static final Color BRAND = new Color(0x1a, 0x3c, 0x6e);

    public static void generate(User user, File outFile) throws IOException {
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(new PDRectangle(CARD_WIDTH, CARD_HEIGHT));
            doc.addPage(page);

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                // Header band
                cs.setNonStrokingColor(BRAND);
                cs.addRect(0, CARD_HEIGHT - 18, CARD_WIDTH, 18);
                cs.fill();
                cs.setNonStrokingColor(Color.WHITE);
                cs.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 9);
                cs.beginText();
                cs.newLineAtOffset(8, CARD_HEIGHT - 13);
                cs.showText("EMERGENCY HEALTH CARD");
                cs.endText();
                cs.setNonStrokingColor(Color.BLACK);

                float photoSize = 46;
                float photoX = CARD_WIDTH - photoSize - 8;
                float photoY = CARD_HEIGHT - 18 - photoSize - 6;

                if (user.hasProfilePicture()) {
                    try {
                        var img = ImageIO.read(new ByteArrayInputStream(user.getProfilePicture()));
                        if (img != null) {
                            PDImageXObject pdImage = LosslessFactory.createFromImage(doc, img);
                            cs.drawImage(pdImage, photoX, photoY, photoSize, photoSize);
                        }
                    } catch (Exception ignored) {
                        // fall through - card still renders without a photo
                    }
                } else {
                    cs.setStrokingColor(Color.GRAY);
                    cs.addRect(photoX, photoY, photoSize, photoSize);
                    cs.stroke();
                }

                float textWidth = CARD_WIDTH - photoSize - 24;
                float y = CARD_HEIGHT - 32;
                PDType1Font label = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                PDType1Font body = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                y = row(cs, label, body, 8, y, "Name:", user.getName(), textWidth);
                y = row(cs, label, body, 8, y, "Age / Gender:", user.getAge() + " / " + nz(user.getGender()), textWidth);
                y = row(cs, label, body, 8, y, "Blood Group:", nz(user.getBloodGroup()), textWidth);
                y = row(cs, label, body, 8, y, "Conditions:", nz(user.getConditions()), textWidth);
                y = row(cs, label, body, 8, y, "Allergies:", nz(user.getAllergies()), textWidth);
                row(cs, label, body, 8, y, "Emergency:", nz(user.getEmergencyContact()), textWidth);

                cs.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE), 6);
                cs.setNonStrokingColor(Color.GRAY);
                cs.beginText();
                cs.newLineAtOffset(8, 6);
                cs.showText("Generated by BioTrack - not a substitute for professional medical advice.");
                cs.endText();
            }

            doc.save(outFile);
        }
    }

    private static float row(PDPageContentStream cs, PDType1Font labelFont, PDType1Font bodyFont, float size,
                              float y, String label, String value, float maxWidth) throws IOException {
        cs.setFont(labelFont, size);
        cs.beginText();
        cs.newLineAtOffset(8, y);
        cs.showText(label);
        cs.endText();

        cs.setFont(bodyFont, size);
        cs.beginText();
        cs.newLineAtOffset(70, y);
        int maxChars = (int) ((maxWidth) / 3.6);
        String v = value.length() > maxChars ? value.substring(0, Math.max(0, maxChars - 1)) + "." : value;
        cs.showText(v);
        cs.endText();
        return y - 11;
    }

    private static String nz(String s) { return (s == null || s.isBlank()) ? "-" : s; }
}
